name: Daily Scheduler

on:
  schedule:
    # Runs every weekday at 9:29 AM and 4:01 PM Eastern Time (adjusted from UTC)
    - cron: '29 13 * * 1-5'  # 9:29 AM ET (13:29 UTC)
    - cron: '1 20 * * 1-5'   # 4:01 PM ET (20:01 UTC)

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduler script
        run: python scheduler.py
