name: Run Scheduler Twice Daily

on:
  schedule:
    - cron: '30 13 * * 1-5'  # 9:30 AM EST (13:30 UTC)
    - cron: '0 20 * * 1-5'   # 4:00 PM EST (20:00 UTC)
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas cloudscraper python-dotenv

      - name: Run scheduler.py
        run: python scheduler.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
